import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import OrderMedicinesFloater from "@/components/common/OrderMedicinesFloater";

const siteFont = Plus_Jakarta_Sans({
  variable: "--font-site",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "hexacare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${siteFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <main className="flex-1 flex flex-col">
          {children}
        </main>
        <Footer></Footer>

        <OrderMedicinesFloater></OrderMedicinesFloater>
      </body>
    </html>
  );
}